
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kelwa
 */
public class HistoryUI extends javax.swing.JFrame {
    
    String option;
    DefaultTableModel model;
    /**
     * Creates new form HistoryUI
     */
    public HistoryUI() {
        initComponents();
    }
    
    public HistoryUI(String option)
    {
        initComponents();
        this.option = option;
        model = (DefaultTableModel)jTable1.getModel();
        model.addColumn("ISBN");
        model.addColumn("Name");
        model.addColumn("Start Date");
        model.addColumn("End Date");
        model.addColumn("Returned");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(".. Histroy");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBack)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(bBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals(""))
            JOptionPane.showMessageDialog(this, "You must but User ID.", "Empty Feild", JOptionPane.WARNING_MESSAGE); 
        else
        {
            if (option.equals("STUDENT"))
            {
                int index = Library.isAvailable(Integer.parseInt(jTextField1.getText()), option);
                if (index == -1)
                    JOptionPane.showMessageDialog(this, "Student not found.", "Not Found", JOptionPane.WARNING_MESSAGE);
                else
                {
                    String type = Library.students.get(index).getClass().getName();
                    model.setRowCount(Library.records.size());
                    int row = 0;
                    int col;
                    for (Borrow r : Library.records) {
                        if (Library.students.get(index).getId() == r.getId() && r.getType().equals("STUDENT")) 
                        {
                                col = 0;
                                model.setValueAt(r.getIsbn(), row, col++);
                                model.setValueAt(r.getName(), row, col++);
                                model.setValueAt(r.getStartDate(), row, col++);
                                model.setValueAt(r.getEndDate(), row, col++);
                                model.setValueAt(r.checkStatus(), row, col++);
                                row++;
                        }
	        }
                    model.setRowCount(row);
                }
            }
            else
            {
                int index = Library.isAvailable(Integer.parseInt(jTextField1.getText()), option);
                if (index == -1)
                    JOptionPane.showMessageDialog(this, "Professor not found.", "Not Found", JOptionPane.WARNING_MESSAGE);
                else
                {
                    String type = Library.professors.get(index).getClass().getName();
                    model.setRowCount(Library.records.size());
                    int row = 0;
                    int col;
                    for (Borrow r : Library.records) {
                        if (Library.professors.get(index).getId() == r.getId() && r.getType().equals("PROFESSOR")) 
                        {
                                col = 0;
                                model.setValueAt(r.getIsbn(), row, col++);
                                model.setValueAt(r.getName(), row, col++);
                                model.setValueAt(r.getStartDate(), row, col++);
                                model.setValueAt(r.getEndDate(), row, col++);
                                model.setValueAt(r.checkStatus(), row, col++);
                                row++;
                        }
	        }
                    model.setRowCount(row);
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
